image: bradlhart/sample-return-values:v0.0.5

ports:
- port: 3000
  onOpen: ignore
- port: 8000
  onOpen: open-preview
- port: 8080
  onOpen: ignore
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- before: cd webapp
  init: yarn
  command: nginx -c $PWD/.gitpod.nginx.conf; yarn startInGitpod
- before: cleos wallet unlock --password </password
  command: nodeos --config-dir $PWD/eosio/chain/config --data-dir $PWD/eosio/chain/data -e -p eosio --plugin eosio::chain_api_plugin --contracts-console
